export const currencies = {
  USD: "Dólar Estadounidense",
  EUR: "Euro",
  GBP: "Libra Esterlina",
  JPY: "Yen Japonés",
  AUD: "Dólar Australiano",
  CAD: "Dólar Canadiense",
  CHF: "Franco Suizo",
  CNY: "Yuan Chino",
  SEK: "Corona Sueca",
  NZD: "Dólar Neozelandés",
  MXN: "Peso Mexicano",
  SGD: "Dólar de Singapur",
  HKD: "Dólar de Hong Kong",
  NOK: "Corona Noruega",
  KRW: "Won Surcoreano",
  TRY: "Lira Turca",
  RUB: "Rublo Ruso",
  INR: "Rupia India",
  BRL: "Real Brasileño",
  ZAR: "Rand Sudafricano",
  AED: "Dirham de los Emiratos",
  ARS: "Peso Argentino",
  CLP: "Peso Chileno",
  COP: "Peso Colombiano",
  PEN: "Sol Peruano",
  VEF: "Bolívar Venezolano",
  UYU: "Peso Uruguayo",
  PYG: "Guaraní Paraguayo",
  BOB: "Boliviano",
  DOP: "Peso Dominicano",
  CRC: "Colón Costarricense",
  GTQ: "Quetzal Guatemalteco",
  HNL: "Lempira Hondureño",
  NIO: "Córdoba Nicaragüense",
  PAB: "Balboa Panameño",
  VES: "Bolívar Soberano",
};

export const currencySymbols = {
  USD: "$",
  EUR: "€",
  GBP: "£",
  JPY: "¥",
  AUD: "A$",
  CAD: "C$",
  CHF: "CHF",
  CNY: "¥",
  SEK: "kr",
  NZD: "NZ$",
  MXN: "MX$",
  SGD: "S$",
  HKD: "HK$",
  NOK: "kr",
  KRW: "₩",
  TRY: "₺",
  RUB: "₽",
  INR: "₹",
  BRL: "R$",
  ZAR: "R",
  AED: "د.إ",
  ARS: "$",
  CLP: "$",
  COP: "$",
  PEN: "S/",
  VEF: "Bs.",
  UYU: "$U",
  PYG: "₲",
  BOB: "Bs.",
  DOP: "RD$",
  CRC: "₡",
  GTQ: "Q",
  HNL: "L",
  NIO: "C$",
  PAB: "B/.",
  VES: "Bs.S",
};

export const currencyFlags = {
  USD: "🇺🇸",
  EUR: "🇪🇺",
  GBP: "🇬🇧",
  JPY: "🇯🇵",
  AUD: "🇦🇺",
  CAD: "🇨🇦",
  CHF: "🇨🇭",
  CNY: "🇨🇳",
  SEK: "🇸🇪",
  NZD: "🇳🇿",
  MXN: "🇲🇽",
  SGD: "🇸🇬",
  HKD: "🇭🇰",
  NOK: "🇳🇴",
  KRW: "🇰🇷",
  TRY: "🇹🇷",
  RUB: "🇷🇺",
  INR: "🇮🇳",
  BRL: "🇧🇷",
  ZAR: "🇿🇦",
  AED: "🇦🇪",
  ARS: "🇦🇷",
  CLP: "🇨🇱",
  COP: "🇨🇴",
  PEN: "🇵🇪",
  VEF: "🇻🇪",
  UYU: "🇺🇾",
  PYG: "🇵🇾",
  BOB: "🇧🇴",
  DOP: "🇩🇴",
  CRC: "🇨🇷",
  GTQ: "🇬🇹",
  HNL: "🇭🇳",
  NIO: "🇳🇮",
  PAB: "🇵🇦",
  VES: "🇻🇪",
};

export const popularCurrencies = [
  "USD",
  "EUR",
  "GBP",
  "JPY",
  "AUD",
  "CAD",
  "MXN",
  "BRL",
  "ARS",
  "CLP",
  "COP",
  "PEN",
];
